[build]
  # Use a custom build command for Python applications
  command = "pip install -r requirements.txt && python freeze.py"
  publish = "build"  # You may not need this for Python, but it's often used for static sites

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
