[build]
  environment = { PYTHON_VERSION = "3.12.7" }
  command = "pip install -r requirements.txt && gunicorn -b 0.0.0.0:8080 app:app"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
